--- #YAML:1.0
name:               NRD-Daemon
version:            0.02
abstract:           Nagios Result Distributor
author:
    - Jose Luis Martinez (jlmartinez@capside.com)
license:            gpl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Clone:             0
    Crypt::Blowfish:   0
    Crypt::CBC:        0
    JSON::XS:          0
    Net::CIDR:         0
    Net::Server:       0
    Parallel::Forker:  0
    Test::Simple:      0.44
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
